//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_TableManagement.MyResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wpf_TableManagement.MyResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click menu to add to order..
        /// </summary>
        public static string addMenu {
            get {
                return ResourceManager.GetString("addMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click on table to manage orders.
        /// </summary>
        public static string ClickTable {
            get {
                return ResourceManager.GetString("ClickTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string FlowDirection {
            get {
                return ResourceManager.GetString("FlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en:English,bn:বাংলা,ar:اَلْعَرَبِيَّةُ.
        /// </summary>
        public static string lnguages {
            get {
                return ResourceManager.GetString("lnguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drinks,Mains,Desserts.
        /// </summary>
        public static string menuItems {
            get {
                return ResourceManager.GetString("menuItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string messageinfo {
            get {
                return ResourceManager.GetString("messageinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Bill.
        /// </summary>
        public static string PayBill {
            get {
                return ResourceManager.GetString("PayBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart application to change language.
        /// </summary>
        public static string restartAlert {
            get {
                return ResourceManager.GetString("restartAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seats.
        /// </summary>
        public static string seats {
            get {
                return ResourceManager.GetString("seats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an item first.
        /// </summary>
        public static string selToDel {
            get {
                return ResourceManager.GetString("selToDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose language.
        /// </summary>
        public static string TbkChooseLanguage {
            get {
                return ResourceManager.GetString("TbkChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter booking name to search.
        /// </summary>
        public static string TbkEnterName {
            get {
                return ResourceManager.GetString("TbkEnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itm.
        /// </summary>
        public static string TbkItem {
            get {
                return ResourceManager.GetString("TbkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage order for Table.
        /// </summary>
        public static string TbkManageOrder {
            get {
                return ResourceManager.GetString("TbkManageOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string TbkOrders {
            get {
                return ResourceManager.GetString("TbkOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string TbkPrice {
            get {
                return ResourceManager.GetString("TbkPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string TbkQty {
            get {
                return ResourceManager.GetString("TbkQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total   €.
        /// </summary>
        public static string TbkTotal {
            get {
                return ResourceManager.GetString("TbkTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Status.
        /// </summary>
        public static string tblBlck {
            get {
                return ResourceManager.GetString("tblBlck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your total bill is: € .
        /// </summary>
        public static string totBill {
            get {
                return ResourceManager.GetString("totBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Management.
        /// </summary>
        public static string windowTitle {
            get {
                return ResourceManager.GetString("windowTitle", resourceCulture);
            }
        }
    }
}
